INSERT INTO ROASTTYPE (id, TYPE_NAME) VALUES (1, '淺焙');
INSERT INTO ROASTTYPE (id, TYPE_NAME) VALUES (2, '中焙');
INSERT INTO ROASTTYPE (id, TYPE_NAME) VALUES (3, '深焙');

INSERT INTO PRODUCT_ROASTTYPE (PRODUCT_ID, ROASTTYPES_ID) VALUES (1, 1);
INSERT INTO PRODUCT_ROASTTYPE (PRODUCT_ID, ROASTTYPES_ID) VALUES (1, 2);
INSERT INTO PRODUCT_ROASTTYPE (PRODUCT_ID, ROASTTYPES_ID) VALUES (1, 3);

INSERT INTO PRODUCT_ROASTTYPE (PRODUCT_ID, ROASTTYPES_ID) VALUES (2, 3);

INSERT INTO PRODUCT_ROASTTYPE (PRODUCT_ID, ROASTTYPES_ID) VALUES (3, 2);
INSERT INTO PRODUCT_ROASTTYPE (PRODUCT_ID, ROASTTYPES_ID) VALUES (3, 3);

INSERT INTO PRODUCT_ROASTTYPE (PRODUCT_ID, ROASTTYPES_ID) VALUES (4, 2);
INSERT INTO PRODUCT_ROASTTYPE (PRODUCT_ID, ROASTTYPES_ID) VALUES (4, 3);

INSERT INTO PRODUCT_ROASTTYPE (PRODUCT_ID, ROASTTYPES_ID) VALUES (5, 2);
INSERT INTO PRODUCT_ROASTTYPE (PRODUCT_ID, ROASTTYPES_ID) VALUES (5, 3);

INSERT INTO PRODUCT_ROASTTYPE (PRODUCT_ID, ROASTTYPES_ID) VALUES (6, 1);

