INSERT INTO Product (id, NAME, IMG_NAME, UNIT_PRICE, IN_STOCK_QTY) VALUES (1, '挪亞咖啡', 1, 250, 10);
INSERT INTO Product (id, NAME, IMG_NAME, UNIT_PRICE, IN_STOCK_QTY) VALUES (2, '方舟咖啡', 2, 250, 20);
INSERT INTO Product (id, NAME, IMG_NAME, UNIT_PRICE, IN_STOCK_QTY) VALUES (3, '丹提咖啡', 3, 250, 30);
INSERT INTO Product (id, NAME, IMG_NAME, UNIT_PRICE, IN_STOCK_QTY) VALUES (4, '紅茶', 4, 150, 50);
INSERT INTO Product (id, NAME, IMG_NAME, UNIT_PRICE, IN_STOCK_QTY) VALUES (5, '綠茶', 5, 100, 60);
